MvcTicSys/MvcTicSys/Controllers/AdminOnaylarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTicSys;

namespace MvcTicSys.Controllers
{ 
    public class AdminOnaylarController : Controller
    {
        private DBTicketSystemEntities db = new DBTicketSystemEntities();

        //
        // GET: /AdminOnaylar/

        public ViewResult Index()
        {
            return View(db.Tbl_Onaylar.ToList());
        }

        //
        // GET: /AdminOnaylar/Details/5

        public ViewResult Details(int id)
        {
            Tbl_Onaylar tbl_onaylar = db.Tbl_Onaylar.Single(t => t.OnayID == id);
            return View(tbl_onaylar);
        }

        //
        // GET: /AdminOnaylar/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /AdminOnaylar/Create

        [HttpPost]
        public ActionResult Create(Tbl_Onaylar tbl_onaylar)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Onaylar.AddObject(tbl_onaylar);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tbl_onaylar);
        }
        
        //
        // GET: /AdminOnaylar/Edit/5
 
        public ActionResult Edit(int id)
        {
            Tbl_Onaylar tbl_onaylar = db.Tbl_Onaylar.Single(t => t.OnayID == id);
            return View(tbl_onaylar);
        }

        //
        // POST: /AdminOnaylar/Edit/5

        [HttpPost]
        public ActionResult Edit(Tbl_Onaylar tbl_onaylar)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Onaylar.Attach(tbl_onaylar);
                db.ObjectStateManager.ChangeObjectState(tbl_onaylar, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_onaylar);
        }

        //
        // GET: /AdminOnaylar/Delete/5
 
        public ActionResult Delete(int id)
        {
            Tbl_Onaylar tbl_onaylar = db.Tbl_Onaylar.Single(t => t.OnayID == id);
            return View(tbl_onaylar);
        }

        //
        // POST: /AdminOnaylar/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Tbl_Onaylar tbl_onaylar = db.Tbl_Onaylar.Single(t => t.OnayID == id);
            db.Tbl_Onaylar.DeleteObject(tbl_onaylar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcTicSys/MvcTicSys/Controllers/AdminSikayetlerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTicSys;

namespace MvcTicSys.Controllers
{ 
    public class AdminSikayetlerController : Controller
    {
        private DBTicketSystemEntities db = new DBTicketSystemEntities();

        //
        // GET: /AdminSikayetler/

        public ViewResult Index()
        {
            var tbl_sikayetler = db.Tbl_Sikayetler.Include("Tbl_Kullanicilar").Include("Tbl_Onaylar");
            return View(tbl_sikayetler.ToList());
        }

        //
        // GET: /AdminSikayetler/Details/5

        public ViewResult Details(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            return View(tbl_sikayetler);
        }

        //
        // GET: /AdminSikayetler/Create

        public ActionResult Create()
        {
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi");
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay");
            return View();
        } 

        //
        // POST: /AdminSikayetler/Create

        [HttpPost]
        public ActionResult Create(Tbl_Sikayetler tbl_sikayetler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Sikayetler.AddObject(tbl_sikayetler);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        }
        
        //
        // GET: /AdminSikayetler/Edit/5
 
        public ActionResult Edit(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        }

        //
        // POST: /AdminSikayetler/Edit/5

        [HttpPost]
        public ActionResult Edit(Tbl_Sikayetler tbl_sikayetler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Sikayetler.Attach(tbl_sikayetler);
                db.ObjectStateManager.ChangeObjectState(tbl_sikayetler, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        }

        //
        // GET: /AdminSikayetler/Delete/5
 
        public ActionResult Delete(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            return View(tbl_sikayetler);
        }

        //
        // POST: /AdminSikayetler/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            db.Tbl_Sikayetler.DeleteObject(tbl_sikayetler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcTicSys/MvcTicSys/Controllers/AdminYetkilerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTicSys;

namespace MvcTicSys.Controllers
{ 
    public class AdminYetkilerController : Controller
    {
        private DBTicketSystemEntities db = new DBTicketSystemEntities();

        //
        // GET: /AdminYetkiler/

        public ViewResult Index()
        {
            return View(db.Tbl_Yetkiler.ToList());
        }

        //
        // GET: /AdminYetkiler/Details/5

        public ViewResult Details(int id)
        {
            Tbl_Yetkiler tbl_yetkiler = db.Tbl_Yetkiler.Single(t => t.YetkiKodu == id);
            return View(tbl_yetkiler);
        }

        //
        // GET: /AdminYetkiler/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /AdminYetkiler/Create

        [HttpPost]
        public ActionResult Create(Tbl_Yetkiler tbl_yetkiler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Yetkiler.AddObject(tbl_yetkiler);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tbl_yetkiler);
        }
        
        //
        // GET: /AdminYetkiler/Edit/5
 
        public ActionResult Edit(int id)
        {
            Tbl_Yetkiler tbl_yetkiler = db.Tbl_Yetkiler.Single(t => t.YetkiKodu == id);
            return View(tbl_yetkiler);
        }

        //
        // POST: /AdminYetkiler/Edit/5

        [HttpPost]
        public ActionResult Edit(Tbl_Yetkiler tbl_yetkiler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Yetkiler.Attach(tbl_yetkiler);
                db.ObjectStateManager.ChangeObjectState(tbl_yetkiler, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_yetkiler);
        }

        //
        // GET: /AdminYetkiler/Delete/5
 
        public ActionResult Delete(int id)
        {
            Tbl_Yetkiler tbl_yetkiler = db.Tbl_Yetkiler.Single(t => t.YetkiKodu == id);
            return View(tbl_yetkiler);
        }

        //
        // POST: /AdminYetkiler/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Tbl_Yetkiler tbl_yetkiler = db.Tbl_Yetkiler.Single(t => t.YetkiKodu == id);
            db.Tbl_Yetkiler.DeleteObject(tbl_yetkiler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcTicSys/MvcTicSys/Controllers/UserEkraniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTicSys;

namespace MvcTicSys.Controllers
{ 
    public class UserEkraniController : Controller
    {
        private DBTicketSystemEntities db = new DBTicketSystemEntities();
 
        public ViewResult Index()
        {
            var tbl_sikayetler = db.Tbl_Sikayetler.Include("Tbl_Kullanicilar").Include("Tbl_Onaylar");
            return View(tbl_sikayetler.ToList());
        }

        public ViewResult Details(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            return View(tbl_sikayetler);
        }

        public ActionResult Create()
        {
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi");
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay");
            return View();
        } 

        [HttpPost]
        public ActionResult Create(Tbl_Sikayetler tbl_sikayetler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Sikayetler.AddObject(tbl_sikayetler);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        } 
 
        public ActionResult Edit(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        } 

        [HttpPost]
        public ActionResult Edit(Tbl_Sikayetler tbl_sikayetler)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Sikayetler.Attach(tbl_sikayetler);
                db.ObjectStateManager.ChangeObjectState(tbl_sikayetler, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KullaniciID = new SelectList(db.Tbl_Kullanicilar, "KullaniciID", "KullaniciAdi", tbl_sikayetler.KullaniciID);
            ViewBag.Onay = new SelectList(db.Tbl_Onaylar, "OnayID", "Onay", tbl_sikayetler.Onay);
            return View(tbl_sikayetler);
        }
 
        public ActionResult Delete(int id)
        {
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            return View(tbl_sikayetler);
        }
         
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Tbl_Sikayetler tbl_sikayetler = db.Tbl_Sikayetler.Single(t => t.SikayetID == id);
            db.Tbl_Sikayetler.DeleteObject(tbl_sikayetler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcTicSys/MvcTicSys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
                    <h1>Ticket System </h1>
                    
                               
            <div id="logindisplay">
             
               @if (Request.IsAuthenticated)
               {
                   <strong>Sisteme Hosgeldiniz; @Html.Encode(User.Identity.Name)</strong>
                   @Html.ActionLink("Cikis", "Cikis", "KullaniciGirisi");
                <ul id="menu">
                    <li>@Html.ActionLink("Sikayetler", "Index", "UserEkrani")</li>
                </ul>
               }
               else
               {
           
                <ul id="menu">
                    <li>@Html.ActionLink("Kullanici Kayit", "Create", "YeniKullaniciKaydi")</li>
                    <li>@Html.ActionLink("Kullanici Girisi", "Giris", "KullaniciGirisi")</li>
                </ul>
               }
               </div>

        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

MvcTicSys/MvcTicSys/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
                    <h1>Ticket System - Admin Paneli</h1>
           
            <div id="logindisplay">
             
               @if (Request.IsAuthenticated)
               {
                   <strong>Sisteme Hosgeldiniz; @Html.Encode(User.Identity.Name)</strong>
                   @Html.ActionLink("Cikis", "Cikis", "KullaniciGirisi");
               <ul id="menu">
                    <li>@Html.ActionLink("Kullanicilar", "Index", "AdminKullanicilar")</li>
                    <li>@Html.ActionLink("Sikayetler", "Index", "AdminSikayetler")</li>
                    <li>@Html.ActionLink("Onaylar", "Index", "AdminOnaylar")</li>
                    <li>@Html.ActionLink("Yetkiler", "Index", "AdminYetkiler")</li>
                </ul>
               }
               else
               {
           
                <ul id="menu">  
                    <li>@Html.ActionLink("Kullanici Kayit", "Create", "YeniKullaniciKaydi")</li>
                    <li>@Html.ActionLink("Kullanici Girisi", "Giris", "KullaniciGirisi")</li>
                </ul>
             
               }
               </div>

        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

MvcTicSys/MvcTicSys/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}